server:
    port: 8084
application:
  welcome:
    message: This is an example
## Spring datasource configuration
spring:
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=1;DB_CLOSE_ON_EXIT=False
    username: sa
    password: sa
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    
## Eureka client configuration
eureka:
  client:
    eureka-server-u-r-l-context: http://localhost:8083/eureka
    service-url:
      defaultZone: http://localhost:8083/eureka
